/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import dao.Conexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabim
 */
public class TelaAgenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        mostra_agenda();
    }

   public ArrayList<Agen> agenList(){
        ArrayList<Agen> agendaList = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Inicial;user=pets;password=123");
            String query3 = "SELECT Agenda.AgendaDia, Agenda.AgendaHora, Agenda.AgendaCliID, Agenda.AgendaPetID, Agenda.Servico, Cliente.CliID, Cliente.CliNome, Pet.PetCliID, Pet.PetNome FROM Agenda, Cliente, Pet WHERE Agenda.AgendaCliID = Cliente.CliID AND Agenda.AgendaPetID = Pet.PetCliID";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query3);
            Agen agenda;
            while(rs.next()){
                agenda = new Agen(rs.getString("AgendaDia"), rs.getString("AgendaHora"), rs.getString("CliNome"), rs.getString("PetNome"),  rs.getString("Servico"));
                agendaList.add(agenda);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return agendaList;
    }
   
    public void mostra_agenda(){
        ArrayList<Agen> list = agenList();
        DefaultTableModel model = (DefaultTableModel)jTabela_Mostra_Agenda.getModel();
        Object[] row = new Object[4];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getAgendaDia() + " " +list.get(i).getAgendaHora();
            row[1] = list.get(i).getCliNome();
            row[2] = list.get(i).getPetNome();
            row[3] = list.get(i).getServico();
            model.addRow(row);
        }
    }
           
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Editar = new javax.swing.JLabel();
        Novo = new javax.swing.JLabel();
        setinha = new javax.swing.JLabel();
        BtEditar = new javax.swing.JLabel();
        BtNovo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela_Mostra_Agenda = new javax.swing.JTable();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Editar.setFont(new java.awt.Font("Brush Script MT", 0, 34)); // NOI18N
        Editar.setText("Editar Atendimento");
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 230, 40));

        Novo.setFont(new java.awt.Font("Brush Script MT", 0, 34)); // NOI18N
        Novo.setText("Novo Atendimento");
        getContentPane().add(Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 210, 40));

        setinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setinhaMouseClicked(evt);
            }
        });
        getContentPane().add(setinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        BtEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 260, 100));

        BtNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtNovo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 260, 100));

        jTabela_Mostra_Agenda.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jTabela_Mostra_Agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horário", "Dono", "Pet", "Tipo de Serviço"
            }
        ));
        jTabela_Mostra_Agenda.setRowHeight(25);
        jScrollPane1.setViewportView(jTabela_Mostra_Agenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 910, -1));
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1011, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setinhaMouseClicked
        TelaPrincipal Principal = new TelaPrincipal();
        Principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_setinhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtEditar;
    private javax.swing.JLabel BtNovo;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Novo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela_Mostra_Agenda;
    private javax.swing.JLabel setinha;
    // End of variables declaration//GEN-END:variables
}
