/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Cadastro;

import dao.Conexao;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabim
 */
public class AgendaCadastro extends javax.swing.JFrame {

    /** Creates new form FornCadastro */
    public AgendaCadastro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Horario = new javax.swing.JLabel();
        Dono = new javax.swing.JLabel();
        Serv = new javax.swing.JLabel();
        Pet = new javax.swing.JLabel();
        BtSair = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        dono = new javax.swing.JTextField();
        serv = new javax.swing.JTextField();
        pet = new javax.swing.JTextField();
        hr = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Horario.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Horario.setText("Horário");
        getContentPane().add(Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 70, 30));

        Dono.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Dono.setText("RG Dono");
        getContentPane().add(Dono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 30));

        Serv.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Serv.setText("Serviço");
        getContentPane().add(Serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 30));

        Pet.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Pet.setText("Pet");
        getContentPane().add(Pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 60, 30));

        BtSair.setBackground(new java.awt.Color(204, 204, 255));
        BtSair.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        BtSair.setText("Sair");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });
        getContentPane().add(BtSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, 40));

        BtSalvar.setBackground(new java.awt.Color(204, 204, 255));
        BtSalvar.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 110, 40));

        dono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donoActionPerformed(evt);
            }
        });
        getContentPane().add(dono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 190, 30));

        serv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        serv.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 190, 30));

        pet.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 190, 30));

        hr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hr.setText("0:0");
        hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrActionPerformed(evt);
            }
        });
        getContentPane().add(hr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, 30));

        dia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setText("0-0-0");
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, 30));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setText("Dia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, 30));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\planodefundo3.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 517, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donoActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        String rg = dono.getText();
        String Dia = dia.getText();
        String horario=hr.getText(); 
        String nomePet=pet.getText();
        String servico = serv.getText();
        int idPet = 0,idDono = 0;
        try{
            Conexao conexao = new Conexao();
            String selecionado = "SELECT PetID,PetNome,PetCliID FROM Inicial.dbo.Pet WHERE PetCliID = (SELECT CliID FROM Inicial.dbo.Cliente WHERE CliRG = '"+rg+"') AND PetNome LIKE '%"+nomePet+"%'" ;
            ResultSet rs = conexao.Pesquisar(selecionado);
            
            if(rs.next()){
                idPet = rs.getInt("PetID");
                idDono = rs.getInt("PetCliID");
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        if(idPet!=0){
            try{
                Conexao conexao = new Conexao();
                String selecionado2 = "INSERT INTO Inicial.dbo.Agenda VALUES ('"+Dia+"','"+horario+"',"+idDono+","+idPet+",'"+servico+"')" ;
                conexao.Salvar(selecionado2);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
           dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Cadastro nao encontrado!");
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        dispose();
    }//GEN-LAST:event_BtSairActionPerformed

    private void hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSair;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JLabel Dono;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Horario;
    private javax.swing.JLabel Pet;
    private javax.swing.JLabel Serv;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField dono;
    private javax.swing.JTextField hr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pet;
    private javax.swing.JTextField serv;
    // End of variables declaration//GEN-END:variables

}
