/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.Cadastro;
import dao.Conexao;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Gabim
 */
public class PetsEditar extends javax.swing.JFrame {
    int CliID=0,PetID=0;
    /** Creates new form FornCadastro */
    public PetsEditar(int IDCli,int IDPet) {
        initComponents();
        CliID=IDCli;
        PetID = IDPet;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Sucesso = new javax.swing.JLabel();
        sim = new javax.swing.JRadioButton();
        nao = new javax.swing.JRadioButton();
        Esp = new javax.swing.JLabel();
        Nm = new javax.swing.JLabel();
        raca = new javax.swing.JLabel();
        Raca1 = new javax.swing.JLabel();
        BtExcluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        Especie = new javax.swing.JTextField();
        Raca = new javax.swing.JTextField();
        NomePet = new javax.swing.JTextField();
        Doenca = new javax.swing.JTextField();
        RG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dia = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        Sexo = new javax.swing.JComboBox<>();
        ano = new javax.swing.JTextField();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sucesso.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        getContentPane().add(Sucesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 160, 30));

        buttonGroup1.add(sim);
        sim.setText("Sim");
        getContentPane().add(sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        buttonGroup1.add(nao);
        nao.setText("Não");
        getContentPane().add(nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        Esp.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Esp.setText("Espécie");
        getContentPane().add(Esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 30));

        Nm.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Nm.setText("Nome");
        getContentPane().add(Nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 40));

        raca.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        raca.setText("Doença");
        getContentPane().add(raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 30));

        Raca1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        Raca1.setText("Raça");
        getContentPane().add(Raca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, 30));

        BtExcluir.setBackground(new java.awt.Color(204, 204, 255));
        BtExcluir.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 120, 40));

        BtCancelar.setBackground(new java.awt.Color(204, 204, 255));
        BtCancelar.setFont(new java.awt.Font("Baskerville Old Face", 0, 22)); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 110, 40));

        BtSalvar.setBackground(new java.awt.Color(204, 204, 255));
        BtSalvar.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        BtSalvar.setText("Editar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 110, 40));

        Especie.setEditable(false);
        Especie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(Especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 190, 30));

        Raca.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Raca.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(Raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 30));

        NomePet.setEditable(false);
        NomePet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(NomePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 30));
        getContentPane().add(Doenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 210, 30));

        RG.setEditable(false);
        getContentPane().add(RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 140, 30));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 40, 30));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setText("Data do Nascimento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel5.setText("Castrado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 30));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel6.setText("RG do Dono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 100, 30));

        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 60, 30));

        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, 30));

        Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fêmea", "Macho" }));
        getContentPane().add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 80, 30));

        ano.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ano.setText("Ano");
        getContentPane().add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 70, 30));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\planodefundo3.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 517, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
         String nome = NomePet.getText();
        String especie = Especie.getText();
        String raca = Raca.getText();
        String doenca = Doenca.getText();
        String sexoselect = Sexo.getSelectedItem().toString();
        String rgDono=RG.getText();
        String data=dia.getSelectedItem().toString() + '-'+ mes.getSelectedItem().toString()+'-'+ano.getText();
        char sexo;
        char castrado;
        if(sexoselect=="Macho"){
            sexo='M';
        }
        else{
            sexo='F';
        }
        if(nao.isSelected()){
            castrado='N';
        }
        else{
            castrado='S';
        }           
        String query="UPDATE Inicial.dbo.Pet SET PetSexo ='"+sexo+"', PetCast='"+castrado+"', Petraca='"+raca+"', PetDoen='"+doenca+"', PetData='"+data+"' WHERE PetID="+PetID;
        if(nome!=""){
           Conexao conexao  = new Conexao();
          conexao.Editar(query);
          Sucesso.setVisible(true);
          Sucesso.setText("Salvo com Sucesso!");
          dispose();
        } 
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try{
            Conexao conexao  = new Conexao();
            String excluir = "Delete from Inicial.dbo.Agenda where AgendaPetID="+PetID+"Delete from Inicial.dbo.Pet where PetID="+PetID;
            conexao.Deletar(excluir);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e); 
        }
        dispose();
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            Conexao conexao  = new Conexao();
            String selecionado = "SELECT * FROM Pet WHERE PetID = '"+PetID+"'";
            ResultSet rs = conexao.Pesquisar(selecionado);
            
            if(rs.next()){
                String nome = rs.getString("PetNome");
                NomePet.setText(nome);
                String especie = rs.getString("PetEsp");
                Especie.setText(especie);
                String raca = rs.getString("Petraca");
                Raca.setText(raca);
                String doenca = rs.getString("PetDoen");
                Doenca.setText(doenca);
                String castrado = rs.getString("PetCast");
                if(castrado=="N"){
                    nao.isSelected();
                }
                else{
                    sim.setSelected(rootPaneCheckingEnabled);
                }
                if(rs.getString("PetSexo")=="M"){
                    Sexo.setSelectedItem("Macho");
                }
                else{
                    Sexo.setSelectedItem("Fêmea");
                }                
            }
            selecionado = "SELECT * FROM Cliente WHERE CliID ="+CliID+"";
            rs = conexao.Pesquisar(selecionado);
            if(rs.next()){
                String rg = rs.getString("CliRG");
                RG.setText(rg);
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e); 
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetsEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetsEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetsEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetsEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PetsEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField Doenca;
    private javax.swing.JLabel Esp;
    private javax.swing.JTextField Especie;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Nm;
    private javax.swing.JTextField NomePet;
    public static javax.swing.JTextField RG;
    private javax.swing.JTextField Raca;
    private javax.swing.JLabel Raca1;
    private javax.swing.JComboBox<String> Sexo;
    private javax.swing.JLabel Sucesso;
    private javax.swing.JTextField ano;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JRadioButton nao;
    private javax.swing.JLabel raca;
    private javax.swing.JRadioButton sim;
    // End of variables declaration//GEN-END:variables

}
