/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
/**
 *
 * @author Gabim
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Logo = new javax.swing.JLabel();
        Donos = new javax.swing.JLabel();
        Pets = new javax.swing.JLabel();
        Agenda = new javax.swing.JLabel();
        Produtos = new javax.swing.JLabel();
        Fornecedores = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Funcionarios = new javax.swing.JLabel();
        DataeHora = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Horário", "Dono", "Pet", "Tipo de Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 580, 280));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\Desktop\\PA\\LogoMenor.png")); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        Donos.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Donos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Donos.setText("| Donos |");
        Donos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonosMouseClicked(evt);
            }
        });
        getContentPane().add(Donos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 40));

        Pets.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Pets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Pets.setText("Pets |");
        Pets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PetsMouseClicked(evt);
            }
        });
        getContentPane().add(Pets, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 40));

        Agenda.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Agenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agenda.setText("Agenda |");
        Agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendaMouseClicked(evt);
            }
        });
        getContentPane().add(Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, 40));

        Produtos.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Produtos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produtos.setText("Produtos |");
        getContentPane().add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, 40));

        Fornecedores.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Fornecedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Fornecedores.setText("Fornecedores |");
        Fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FornecedoresMouseClicked(evt);
            }
        });
        getContentPane().add(Fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, 40));

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jButton1.setText("Realizar Compra");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 260, 80));

        Funcionarios.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Funcionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Funcionarios.setText("Funcionários |");
        Funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuncionariosMouseClicked(evt);
            }
        });
        getContentPane().add(Funcionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, 40));

        DataeHora.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        DataeHora.setText("Data e Hora");
        getContentPane().add(DataeHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 180, 60));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\Desktop\\PA\\fundo4.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FornecedoresMouseClicked
        TelaFornecedores Forn = new TelaFornecedores();
        Forn.setVisible(true);
        dispose();
    }//GEN-LAST:event_FornecedoresMouseClicked

    private void AgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgendaMouseClicked
        TelaAgenda Agenda = new TelaAgenda();
        Agenda.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgendaMouseClicked

    private void PetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsMouseClicked
        TelaPets Pets = new TelaPets();
        Pets.setVisible(true);
        dispose();
    }//GEN-LAST:event_PetsMouseClicked

    private void DonosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonosMouseClicked
        TelaDonos Donos = new TelaDonos();
        Donos.setVisible(true);
        dispose();
    }//GEN-LAST:event_DonosMouseClicked

    private void FuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuncionariosMouseClicked
        TelaFuncionarios Func = new TelaFuncionarios();
        Func.setVisible(true);
        dispose();
    }//GEN-LAST:event_FuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agenda;
    private javax.swing.JLabel DataeHora;
    private javax.swing.JLabel Donos;
    private javax.swing.JLabel Fornecedores;
    private javax.swing.JLabel Funcionarios;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Pets;
    private javax.swing.JLabel Produtos;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
