/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cli;
import View.Cadastro.DonoCadastro;
import View.Cadastro.DonoEditar;
import dao.Conexao;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabim
 */
public class TelaDonos extends javax.swing.JFrame {
    ArrayList<Cli> clientes = new ArrayList<>();
    String query;
    int ID;
    /**
     * Creates new form TelaFornecedores
     */
    public TelaDonos() {
        initComponents();
        query= "SELECT c.CliID,c.CliNome,c.CliTel,c.CliEmail,p.PetNome,c.CliRG from Inicial.dbo.Cliente c left join Inicial.dbo.Pet p on p.PetCliID = c.CliID order by c.CliNome";
        clientes = clienteList(query);
        mostra_clientes(clientes);
    }
    
    public ArrayList<Cli> clienteList(String query4){
        ArrayList<Cli> clientesList = new ArrayList<>();
        try{
            Conexao conexao = new Conexao();
            ResultSet rs = conexao.Pesquisar(query4);
            Cli cliente;
            while(rs.next()){
                cliente = new Cli(rs.getInt("CliID"), rs.getString("CliNome"), rs.getString("CliTel"), rs.getString("CliEmail"), rs.getString("PetNome"), rs.getString("CliRG"));
                clientesList.add(cliente);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return clientesList;
        
    }
    
    public void mostra_clientes(ArrayList<Cli> clientes){
        ArrayList<Cli> list = clientes;
        DefaultTableModel model = (DefaultTableModel)jTabela_Mostra_Clientes.getModel();
        Object[] row = new Object[6];
        model.setRowCount(0);
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getCliID();
            row[1] = list.get(i).getCliNome();
            row[2] = list.get(i).getCliTel();
            row[3] = list.get(i).getCliEmail();
            row[4] = list.get(i).getPetNome();
            row[5] = list.get(i).getCliRG();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lupa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DonoSelecionado = new javax.swing.JTextPane();
        ProcuraDono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabela_Mostra_Clientes = new javax.swing.JTable();
        Editar = new javax.swing.JLabel();
        Novo = new javax.swing.JLabel();
        setinha = new javax.swing.JLabel();
        moldura2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Atualizar = new javax.swing.JLabel();
        moldura3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moldura1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lupa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lupa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\lupa2.png")); // NOI18N
        lupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lupaMousePressed(evt);
            }
        });
        getContentPane().add(lupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 100, 70));

        DonoSelecionado.setEditable(false);
        DonoSelecionado.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        DonoSelecionado.setText("Dono Selecionado");
        jScrollPane1.setViewportView(DonoSelecionado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 430, 40));
        getContentPane().add(ProcuraDono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 500, 50));

        jTabela_Mostra_Clientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabela_Mostra_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Email", "Nome do Pet", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela_Mostra_Clientes.setRowHeight(30);
        jTabela_Mostra_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabela_Mostra_ClientesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTabela_Mostra_Clientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 277, 880, 270));

        Editar.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("Editar");
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarMousePressed(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 120, 40));

        Novo.setFont(new java.awt.Font("Brush Script MT", 0, 42)); // NOI18N
        Novo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Novo.setText("Novo");
        Novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NovoMousePressed(evt);
            }
        });
        getContentPane().add(Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 120, 40));

        setinha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\setinha2.png")); // NOI18N
        setinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setinhaMousePressed(evt);
            }
        });
        getContentPane().add(setinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 50));

        moldura2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\botao2.png")); // NOI18N
        getContentPane().add(moldura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\input3.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 630, 70));

        Atualizar.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtualizarMousePressed(evt);
            }
        });
        getContentPane().add(Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 120, 40));

        moldura3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\botao2.png")); // NOI18N
        getContentPane().add(moldura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\input3.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 470, 60));

        moldura1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\botao2.png")); // NOI18N
        getContentPane().add(moldura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\fundo4.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setinhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setinhaMousePressed
        TelaPrincipal Principal = new TelaPrincipal();
        Principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_setinhaMousePressed

    private void lupaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaMousePressed
        query = "SELECT	CliID,CliNome,CliTel,CliEmail,PetNome,CliRG from Inicial.dbo.Cliente left join Inicial.dbo.Pet p on p.PetCliID = CliID WHERE CliNome LIKE '%"+ ProcuraDono.getText()+"%'";
       clientes = clienteList(query);
       mostra_clientes(clientes);
    }//GEN-LAST:event_lupaMousePressed

    private void AtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtualizarMousePressed
       query = "SELECT c.CliID,c.CliNome,c.CliTel,c.CliEmail,p.PetNome,c.CliRG from Inicial.dbo.Cliente c left join Inicial.dbo.Pet p on p.PetCliID = c.CliID order by c.CliNome";
       clientes = clienteList(query);
       mostra_clientes(clientes);
    }//GEN-LAST:event_AtualizarMousePressed

    private void EditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMousePressed
        if(DonoSelecionado.getText()!="Cliente Selecionado"){
           DonoEditar novo = new DonoEditar(ID);
           novo.setVisible(true); 
        }
        else{
            System.out.println("Escolha um cliente!");
        }   
    }//GEN-LAST:event_EditarMousePressed

    private void NovoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoMousePressed
        DonoCadastro novo = new DonoCadastro();
        novo.setVisible(true);
    }//GEN-LAST:event_NovoMousePressed

    private void jTabela_Mostra_ClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabela_Mostra_ClientesMousePressed
        try{
            int row = jTabela_Mostra_Clientes.getSelectedRow();
            String id = (jTabela_Mostra_Clientes.getModel().getValueAt(row, 0).toString());
            String nome = (jTabela_Mostra_Clientes.getModel().getValueAt(row, 1).toString());
            ID = Integer.parseInt(id);
            DonoSelecionado.setText(nome);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTabela_Mostra_ClientesMousePressed
    
    
    private void Transparente(){
        /*jTextField1.setBackground(new Color(0,0,0,0));
        jTextPane1.setBackground(new Color(0,0,0,0));*/
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atualizar;
    private static javax.swing.JTextPane DonoSelecionado;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Novo;
    private javax.swing.JTextField ProcuraDono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabela_Mostra_Clientes;
    private javax.swing.JLabel lupa;
    private javax.swing.JLabel moldura1;
    private javax.swing.JLabel moldura2;
    private javax.swing.JLabel moldura3;
    private javax.swing.JLabel setinha;
    // End of variables declaration//GEN-END:variables
}
