/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Cadastro.Login_Func;
import dao.Conexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabim
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formatterData = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        String dataFormatada = formatterData.format(agora);
        DataDia.setText(dataFormatada);
        mostra_agenda();
    }
    
    public ArrayList<Agen> agenList(){
        ArrayList<Agen> agendaList = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Inicial;user=pets;password=123");
            String query3 = "SELECT Agenda.AgendaDia, Agenda.AgendaHora, Agenda.AgendaCliID, Agenda.AgendaPetID, Agenda.Servico, Cliente.CliID, Cliente.CliNome, Pet.PetCliID, Pet.PetNome FROM Agenda, Cliente, Pet WHERE Agenda.AgendaCliID = Cliente.CliID AND Agenda.AgendaPetID = Pet.PetCliID";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query3);
            Agen agenda;
            while(rs.next()){
                agenda = new Agen(rs.getString("AgendaDia"), rs.getString("AgendaHora"), rs.getString("CliNome"), rs.getString("PetNome"),  rs.getString("Servico"));
                agendaList.add(agenda);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return agendaList;
    }
   
    public void mostra_agenda(){
        ArrayList<Agen> list = agenList();
        DefaultTableModel model = (DefaultTableModel)jTabela_Mostra_Agenda2.getModel();
        Object[] row = new Object[4];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getAgendaDia() + " " +list.get(i).getAgendaHora();
            row[1] = list.get(i).getCliNome();
            row[2] = list.get(i).getPetNome();
            row[3] = list.get(i).getServico();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela_Mostra_Agenda2 = new javax.swing.JTable();
        Logo = new javax.swing.JLabel();
        DataDia = new javax.swing.JLabel();
        Funcionarios = new javax.swing.JLabel();
        Fornecedores = new javax.swing.JLabel();
        Produtos = new javax.swing.JLabel();
        Agenda = new javax.swing.JLabel();
        Pets = new javax.swing.JLabel();
        Donos = new javax.swing.JLabel();
        Comprar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabela_Mostra_Agenda2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabela_Mostra_Agenda2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horário", "Dono", "Pet", "Tipo de Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela_Mostra_Agenda2.setRowHeight(25);
        jScrollPane1.setViewportView(jTabela_Mostra_Agenda2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 580, 280));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\LogoMenor.png")); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        DataDia.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        DataDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(DataDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 260, 60));

        Funcionarios.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Funcionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Funcionarios.setText("Funcionários |");
        Funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FuncionariosMousePressed(evt);
            }
        });
        getContentPane().add(Funcionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 200, 40));

        Fornecedores.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Fornecedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Fornecedores.setText("Fornecedores |");
        Fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FornecedoresMousePressed(evt);
            }
        });
        getContentPane().add(Fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, 40));

        Produtos.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Produtos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produtos.setText("Produtos |");
        Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProdutosMousePressed(evt);
            }
        });
        getContentPane().add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 150, 40));

        Agenda.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Agenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agenda.setText("Agenda |");
        Agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgendaMousePressed(evt);
            }
        });
        getContentPane().add(Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 240, 130, 40));

        Pets.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Pets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Pets.setText("Pets |");
        Pets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PetsMousePressed(evt);
            }
        });
        getContentPane().add(Pets, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 40));

        Donos.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Donos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Donos.setText("| Donos |");
        Donos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DonosMousePressed(evt);
            }
        });
        getContentPane().add(Donos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 40));

        Comprar.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        Comprar.setText("Realizar Compra");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        getContentPane().add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 260, 80));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\fundo4.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        TelaCompras Compras = new TelaCompras();
        Compras.setVisible(true);
        dispose();
    }//GEN-LAST:event_ComprarActionPerformed

    private void DonosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonosMousePressed
        TelaDonos Donos = new TelaDonos();
        Donos.setVisible(true);
        dispose();
    }//GEN-LAST:event_DonosMousePressed

    private void PetsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PetsMousePressed
        TelaPets Pets = new TelaPets();
        Pets.setVisible(true);
        dispose();
    }//GEN-LAST:event_PetsMousePressed

    private void AgendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgendaMousePressed
        TelaAgenda Agenda = new TelaAgenda();
        Agenda.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgendaMousePressed

    private void ProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdutosMousePressed
        TelaProdutos Prod = new TelaProdutos();
        Prod.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProdutosMousePressed

    private void FornecedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FornecedoresMousePressed
        TelaFornecedores Forn = new TelaFornecedores();
        Forn.setVisible(true);
        dispose();
    }//GEN-LAST:event_FornecedoresMousePressed

    private void FuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuncionariosMousePressed
        Login_Func Func = new Login_Func();
        Func.setVisible(true);
        dispose();
    }//GEN-LAST:event_FuncionariosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agenda;
    private javax.swing.JButton Comprar;
    private javax.swing.JLabel DataDia;
    private javax.swing.JLabel Donos;
    private javax.swing.JLabel Fornecedores;
    private javax.swing.JLabel Funcionarios;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Pets;
    private javax.swing.JLabel Produtos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela_Mostra_Agenda2;
    // End of variables declaration//GEN-END:variables
}
