/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Prod;
import dao.Conexao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabim
 */
public class TelaCarrinho extends javax.swing.JFrame {
    private ArrayList<Prod> listaProdutos = new ArrayList<>();
    float totalItem,Total;
    int IDProduto,tamanho,row=-1;
    /**
     * Creates new form TelaAgenda
     */
    public TelaCarrinho(ArrayList<Prod> produtos) {
        initComponents();
        listaProdutos= produtos;
        tamanho=produtos.size();
        mostra_prod(listaProdutos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalCompra = new javax.swing.JTextField();
        Finalizar = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        Itens = new javax.swing.JLabel();
        setinha = new javax.swing.JLabel();
        BtEditar = new javax.swing.JLabel();
        BtCancelar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalCompra.setEditable(false);
        TotalCompra.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        TotalCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 250, 70));

        Finalizar.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        Finalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Finalizar.setText("Finalizar Compra");
        Finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FinalizarMousePressed(evt);
            }
        });
        getContentPane().add(Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 240, 70));

        Cancelar.setFont(new java.awt.Font("Brush Script MT", 0, 34)); // NOI18N
        Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelarMousePressed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 120, 60));

        Valor.setFont(new java.awt.Font("Baskerville Old Face", 0, 42)); // NOI18N
        Valor.setText("Total:");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        Itens.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        Itens.setText("Itens do Carrinho");
        getContentPane().add(Itens, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 270, 50));

        setinha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\setinha2.png")); // NOI18N
        setinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setinhaMousePressed(evt);
            }
        });
        getContentPane().add(setinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        BtEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\botao.png")); // NOI18N
        BtEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 260, 100));

        BtCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\botao2.png")); // NOI18N
        BtCancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 140, 80));

        jTable1.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Preço", "Quantidade", "TotalItem"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 910, 370));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabim\\OneDrive\\Área de Trabalho\\PA\\PA---4S-master\\AnimalsPalace\\src\\main\\java\\imagens\\fundo4.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1011, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        row = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MousePressed

    private void CancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMousePressed
        dispose();
    }//GEN-LAST:event_CancelarMousePressed

    private void FinalizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarMousePressed
        String query,produ,quant;
        int quantidade;
        ArrayList<Prod> list = listaProdutos;
        try{
            Conexao conexao = new Conexao();
            System.out.println("Tam: "+tamanho);
            for(int j=0; j<tamanho; j++){
                produ = (jTable1.getModel().getValueAt(j, 0).toString());
                IDProduto= Integer.parseInt(produ);
                quant= (jTable1.getModel().getValueAt(j, 3).toString());
                quantidade=Integer.parseInt(quant);
                System.out.println("ID: "+IDProduto);
                query="UPDATE Inicial.dbo.Produto SET ProQuant =((SELECT ProQuant from Inicial.dbo.Produto WHERE ProID="+IDProduto+")-"+quantidade+") WHERE ProID="+IDProduto;
                conexao.Editar(query);
            }
            dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_FinalizarMousePressed

    private void setinhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setinhaMousePressed
        TelaPrincipal Principal = new TelaPrincipal();
        Principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_setinhaMousePressed

    public void mostra_prod(ArrayList<Prod> produtos){
        ArrayList<Prod> list = produtos;
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        Total=0;
        for(int i=0; i<produtos.size(); i++){
            row[0] = list.get(i).getProID();
            row[1] = list.get(i).getProNome();
            row[2] = "R$ "+list.get(i).getProPre();
            row[3] = list.get(i).getProQuant();
            totalItem=list.get(i).getProPre()*list.get(i).getProQuant();
            row[4] = totalItem;
            Total+=totalItem;
            model.addRow(row);
        }
        TotalCompra.setText(String.valueOf(Total));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtCancelar;
    private javax.swing.JLabel BtEditar;
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Finalizar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Itens;
    private javax.swing.JTextField TotalCompra;
    private javax.swing.JLabel Valor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel setinha;
    // End of variables declaration//GEN-END:variables
}
